class_names = {
    0: 'ball',
    1: 'down',
    # 2: 'game-objects',
    2: 'left',
    3: 'left_goal',
    4: 'man_city',
    5: 'man_city_gk',
    6: 'man_utd',
    7: 'man_utd_gk',
    8: 'right',
    9: 'right_goal',
    10: 'tri',
    11: 'up',
    12: 'x',
}